### ISSUE TITLE
Z-ordering of multiple objects?

### ISSUE THREAD

**Issue by AstroAndyN** [kevinroast/phoria.js#25]
Hi
First of all, thanks for Phoria.js - i'm having a great time playing with it.

I have stumbled across a bit of a problem and I'm not sure if it is fundamental, or just me misapplying the script library. I have two separate entities (essentially a ring and a cylinder) with the cylinder inside the ring. However, the Z-ordering stage in modelView() only does the Z-ordering for each object, with the result that parts of the ring "behind" the cylinder appear in front: see http://www.astro.ljmu.ac.uk/~amn/PhoriaTest/ltalltest.html

Is there anything that can be done to create suitably rendered nested object like this?

Many thanks
Andy

**Comment by EpicWumbo2048** [comment]
+1
Problem well described.
I've bumped into something similar and worked around it by changing the model and camera angle.
I'm Not sure if you're seeing it, but on mobile Safari for iOS 8.1.2, the torus flips between being entirely in front of and entirely behind the cylinder.

**Comment by kevinroast** [comment]
Yes this is a known limitation of the object sorting processing currently :(

1. Each object is processed individually, sorting of the points/polys as needed to ensure the object itself is rendered correctly.
2. The objects are then sorted by the average Z coordinate for the object and render is called for each object in turn.

This is a design limitation of the library currently that each object is processed individually and then rendering one by one in the scene.

What this needs is a single "render list" of all polygons for the scene which is sorted once before render. I avoided this initially because it was tricky with all the different rendering modes available for objects (many don't use polygons at all).

**Comment by AstroAndyN** [comment]
Thanks for the quick reply Kevin - I'm glad it's not just me being stupid! I'll probably have to resort to another library for this particular task (the final object I'm going to model is quite complicated and has a lot of concave components), but I'm sure I'll be returning to Phoria in the future...

**Comment by kevinroast** [comment]
No problem. If you combine the multiple objects in a single object that will give you the effect you want - but of course there isn't a util function to do that currently.
